export type AppRole =
  | 'admin'
  | 'project_manager'
  | 'engineer'
  | 'accountant'
  | 'contractor'
  | 'viewer';

export const roleDefinitions: Record<AppRole, { label: string; description: string }> = {
  admin: {
    label: 'Admin',
    description: 'Full system access.',
  },
  project_manager: {
    label: 'Project Manager',
    description: 'Owns project delivery and RA bill review flow, without finance settlement control.',
  },
  engineer: {
    label: 'Engineer',
    description: 'Drives site execution, stock, and labour operations.',
  },
  accountant: {
    label: 'Accountant',
    description: 'Owns finance settlement, payment, and secured advance control.',
  },
  contractor: {
    label: 'Contractor',
    description: 'Read-only visibility into assigned execution records.',
  },
  viewer: {
    label: 'Viewer',
    description: 'Read-only oversight across the workspace.',
  },
};

const permissionEquivalenceGroups = [
  ['requisitions:create', 'material_requisitions:create'],
  ['requisitions:approve', 'material_requisitions:update'],
  ['receipts:create', 'material_receipts:create'],
  ['stock:issue', 'material_issues:create', 'material_issues:update'],
  ['stock:adjust', 'material_stock_adjustments:create', 'material_stock_adjustments:update'],
  ['labour:read', 'labours:read'],
  ['labour:create', 'labours:create'],
  ['labour:update', 'labours:update'],
  ['attendance:create', 'labour_attendance:create'],
  ['attendance:approve', 'labour_attendance:update'],
  ['labour_bills:approve', 'labour_bills:update'],
] as const;

const permissionEquivalents = new Map<string, Set<string>>();

for (const group of permissionEquivalenceGroups) {
  const normalizedGroup = new Set(group.map((permission) => permission.trim().toLowerCase()));
  for (const permission of normalizedGroup) {
    permissionEquivalents.set(permission, normalizedGroup);
  }
}

const rolePermissions: Record<AppRole, Set<string>> = {
  admin: new Set(['*']),
  project_manager: new Set([
    'dashboard:read',
    'companies:read',
    'projects:create',
    'projects:read',
    'projects:update',
    'vendors:create',
    'vendors:update',
    'vendors:read',
    'materials:create',
    'materials:update',
    'materials:read',
    'stock_ledger:read',
    'material_stock_adjustments:create',
    'material_stock_adjustments:update',
    'material_stock_adjustments:read',
    'material_issues:create',
    'material_issues:update',
    'material_issues:read',
    'material_receipts:create',
    'material_receipts:update',
    'material_receipts:read',
    'material_requisitions:create',
    'material_requisitions:update',
    'material_requisitions:read',
    'requisitions:create',
    'requisitions:approve',
    'receipts:create',
    'stock:issue',
    'stock:adjust',
    'labour_contractors:create',
    'labour_contractors:update',
    'labour_contractors:read',
    'labours:create',
    'labours:update',
    'labours:read',
    'labour:create',
    'labour:update',
    'labour:read',
    'labour_attendance:create',
    'labour_attendance:update',
    'labour_attendance:read',
    'attendance:create',
    'attendance:approve',
    'labour_productivity:create',
    'labour_productivity:update',
    'labour_productivity:read',
    'labour_bills:create',
    'labour_bills:update',
    'labour_bills:read',
    'labour_bills:approve',
    'labour_advances:create',
    'labour_advances:update',
    'labour_advances:read',
    'contracts:create',
    'contracts:update',
    'contracts:read',
    'documents:create',
    'documents:update',
    'documents:read',
    'secured_advances:read',
    'boq:create',
    'boq:update',
    'boq:read',
    'measurements:create',
    'measurements:read',
    'measurements:update',
    'measurements:submit',
    'measurements:approve',
    'work_done:read',
    'ra_bills:create',
    'ra_bills:read',
    'ra_bills:submit',
    'ra_bills:verify',
    'ra_bills:approve',
    'ra_bills:reject',
    'ra_bills:cancel',
    'ra_bills:finance_hold',
    'payments:read',
    'site_expenses:create',
    'site_expenses:read',
    'site_expenses:update',
    'audit_logs:read',
    'workflows:read',
  ]),
  engineer: new Set([
    'dashboard:read',
    'companies:read',
    'projects:read',
    'projects:update',
    'contracts:read',
    'vendors:read',
    'materials:create',
    'materials:update',
    'materials:read',
    'stock_ledger:read',
    'material_stock_adjustments:create',
    'material_stock_adjustments:update',
    'material_stock_adjustments:read',
    'material_issues:create',
    'material_issues:update',
    'material_issues:read',
    'material_receipts:create',
    'material_receipts:update',
    'material_receipts:read',
    'material_requisitions:create',
    'material_requisitions:update',
    'material_requisitions:read',
    'requisitions:create',
    'requisitions:approve',
    'receipts:create',
    'stock:issue',
    'stock:adjust',
    'labour_contractors:create',
    'labour_contractors:update',
    'labour_contractors:read',
    'labours:create',
    'labours:update',
    'labours:read',
    'labour:create',
    'labour:update',
    'labour:read',
    'labour_attendance:create',
    'labour_attendance:update',
    'labour_attendance:read',
    'attendance:create',
    'attendance:approve',
    'labour_productivity:create',
    'labour_productivity:update',
    'labour_productivity:read',
    'labour_bills:create',
    'labour_bills:update',
    'labour_bills:read',
    'labour_bills:approve',
    'labour_advances:create',
    'labour_advances:update',
    'labour_advances:read',
    'secured_advances:read',
    'documents:create',
    'documents:update',
    'documents:read',
    'boq:create',
    'boq:update',
    'boq:read',
    'measurements:create',
    'measurements:read',
    'measurements:update',
    'measurements:submit',
    'work_done:read',
    'ra_bills:read',
    'payments:read',
    'site_expenses:create',
    'site_expenses:read',
    'site_expenses:update',
    'workflows:read',
  ]),
  accountant: new Set([
    'dashboard:read',
    'companies:read',
    'projects:read',
    'contracts:read',
    'vendors:read',
    'materials:read',
    'stock_ledger:read',
    'material_stock_adjustments:read',
    'material_issues:read',
    'material_receipts:read',
    'material_requisitions:read',
    'labour_contractors:read',
    'labours:read',
    'labour:read',
    'labour_attendance:read',
    'labour_productivity:read',
    'labour_bills:create',
    'labour_bills:update',
    'labour_bills:read',
    'labour_bills:approve',
    'labour_advances:create',
    'labour_advances:update',
    'labour_advances:read',
    'secured_advances:create',
    'secured_advances:update',
    'secured_advances:read',
    'documents:create',
    'documents:update',
    'documents:read',
    'boq:read',
    'measurements:read',
    'work_done:read',
    'ra_bills:create',
    'ra_bills:read',
    'ra_bills:submit',
    'ra_bills:verify',
    'ra_bills:approve',
    'ra_bills:reject',
    'ra_bills:cancel',
    'ra_bills:finance_hold',
    'ra_bills:partially_paid',
    'ra_bills:paid',
    'payments:read',
    'payments:create',
    'payments:approve',
    'payments:release',
    'payments:allocate',
    'site_expenses:create',
    'site_expenses:read',
    'site_expenses:update',
    'site_expenses:approve',
    'site_expenses:pay',
    'audit_logs:read',
    'workflows:read',
  ]),
  contractor: new Set([
    'dashboard:read',
    'companies:read',
    'projects:read',
    'contracts:read',
    'vendors:read',
    'materials:read',
    'stock_ledger:read',
    'material_stock_adjustments:read',
    'material_issues:read',
    'material_receipts:read',
    'material_requisitions:read',
    'labour_contractors:read',
    'labours:read',
    'labour:read',
    'labour_attendance:read',
    'labour_productivity:read',
    'labour_bills:read',
    'labour_advances:read',
    'secured_advances:read',
    'documents:read',
    'boq:read',
    'measurements:read',
    'work_done:read',
    'ra_bills:read',
    'payments:read',
    'site_expenses:read',
  ]),
  viewer: new Set([
    'dashboard:read',
    'companies:read',
    'projects:read',
    'contracts:read',
    'vendors:read',
    'materials:read',
    'stock_ledger:read',
    'material_stock_adjustments:read',
    'material_issues:read',
    'material_receipts:read',
    'material_requisitions:read',
    'labour_contractors:read',
    'labours:read',
    'labour:read',
    'labour_attendance:read',
    'labour_productivity:read',
    'labour_bills:read',
    'labour_advances:read',
    'secured_advances:read',
    'documents:read',
    'boq:read',
    'measurements:read',
    'work_done:read',
    'ra_bills:read',
    'payments:read',
    'site_expenses:read',
  ]),
};

export function normalizeRole(role: string): AppRole {
  const normalized = role.trim().toLowerCase().replace(/\s+/g, '_').replace(/-/g, '_');
  if (normalized in roleDefinitions) {
    return normalized as AppRole;
  }
  return 'viewer';
}

export function getRoleLabel(role: string) {
  return roleDefinitions[normalizeRole(role)].label;
}

export function hasPermissions(role: string, permissions: string[]) {
  const normalizedRole = normalizeRole(role);
  const granted = rolePermissions[normalizedRole];

  if (granted.has('*')) {
    return true;
  }

  return permissions.every((permission) => {
    const normalizedPermission = permission.trim().toLowerCase();
    const aliases = permissionEquivalents.get(normalizedPermission) ?? new Set([normalizedPermission]);
    return Array.from(aliases).some((alias) => granted.has(alias));
  });
}

export function hasRole(role: string, allowedRoles: AppRole[]) {
  return allowedRoles.includes(normalizeRole(role));
}
